#include <limits.h>
#include <cstddef>

#define ABSL_NAMESPACE_BEGIN
#define ABSL_NAMESPACE_END
#define ABSL_INTERNAL_C_SYMBOL(x) x

//#define ABSL_HAVE_BUILTIN(x) 0
#define ABSL_HAVE_BUILTIN(x) __has_builtin(x)

#define ABSL_DLL


#define ABSL_HAVE_TLS 0
#define ABSL_HAVE_STD_IS_TRIVIALLY_DESTRUCTIBLE 0
#define ABSL_HAVE_STD_IS_TRIVIALLY_CONSTRUCTIBLE 0
#define ABSL_HAVE_STD_IS_TRIVIALLY_ASSIGNABLE 0
#define ABSL_HAVE_THREAD_LOCAL 0
#define ABSL_HAVE_INTRINSIC_INT128 0
#define ABSL_HAVE_EXCEPTIONS 0
#define ABSL_HAVE_MMAP 1 // cant build without it
#define ABSL_HAVE_PTHREAD_GETSCHEDPARAM 0
//#define ABSL_HAVE_SCHED_GETCPU 0
#undef ABSL_HAVE_SCHED_GETCPU

#define ABSL_HAVE_SCHED_YIELD 0
#define ABSL_HAVE_SEMAPHORE_H 0
#define ABSL_HAVE_ALARM 0

#define ABSL_IS_BIG_ENDIAN 0
#define ABSL_IS_LITTLE_ENDIAN 1

#define ABSL_HAVE_STD_ANY 0
#define ABSL_HAVE_STD_OPTIONAL 0
#define ABSL_HAVE_STD_VARIANT 0
#define ABSL_HAVE_STD_STRING_VIEW 0
#define ABSL_HAVE_MEMORY_SANITIZER 0
#define ABSL_HAVE_THREAD_SANITIZER 0
#define ABSL_HAVE_ADDRESS_SANITIZER 0
#define ABSL_HAVE_CLASS_TEMPLATE_ARGUMENT_DEDUCTION 0

#define ABSL_OPTION_HARDENED 1

#define ABSL_FORCE_WAITER_MODE ABSL_WAITER_MODE_CONDVAR